import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const graphie = localFont({
  src: [
    {
      path: "../../public/fonts/GraphieRegular.otf",
      weight: "400",
      style: "normal"
    },
    {
      path: "../../public/fonts/GraphieExtraBold.otf",
      weight: "700",
      style: "normal"
    },
  ],
  variable: "--font-graphie"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${graphie.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
